export const SET_SUBSCRIBE_FIELD = 'SET_SUBSCRIBE_FIELD';
export const SUBSCRIBE = 'SUBSCRIBE';
export const SUBSCRIBE_START = 'SUBSCRIBE_START';
export const SUBSCRIBE_FAILURE = 'SUBSCRIBE_FAILURE';
export const SUBSCRIBE_SUCCESS = 'SUBSCRIBE_SUCCESS';
