export const CREATE_ORDER_START = 'CREATE_ORDER_START';
export const CREATE_ORDER_SUCCESS = 'CREATE_ORDER_SUCCESS';
export const CREATE_ORDER_FAILURE = 'CREATE_ORDER_FAILURE';
export const CHANGE_FIELD = 'CHANGE_FIELD';
export const CHANGE_PURCHASE_FORM_STATUS = 'CHANGE_PURCHASE_FORM_STATUS';
